---
permalink: storage/task_data_manage_accounts_work_with_accounts_task.html 
sidebar: sidebar 
keywords: element, solidfire, accounts, create, delete, change, chap, view, edit 
summary: Nei sistemi storage SolidFire, gli account utente consentono ai client di connettersi ai volumi su un nodo. Quando si crea un volume, questo viene assegnato a un account utente specifico. 
---
= Utilizzare gli account con CHAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nei sistemi storage SolidFire, i tenant possono utilizzare gli account per consentire ai client di connettersi ai volumi di un cluster. Un account contiene l'autenticazione CHAP (Challenge-Handshake Authentication Protocol) richiesta per accedere ai volumi assegnati. Quando si crea un volume, questo viene assegnato a un account specifico.

A un account possono essere assegnati fino a duemila volumi, ma un volume può appartenere a un solo account.



== Creare un account

È possibile creare un account per consentire l'accesso ai volumi.

Ogni nome account nel sistema deve essere univoco.

. Selezionare *Gestione* > *account*.
. Fare clic su *Create account* (Crea account).
. Immettere un *Nome utente*.
. Nella sezione *Impostazioni CHAP*, immettere le seguenti informazioni:
+

NOTE: Lasciare vuoti i campi delle credenziali per generare automaticamente una delle due password.

+
** *Initiator Secret* per l'autenticazione della sessione del nodo CHAP.
** *Target Secret* per l'autenticazione della sessione del nodo CHAP.


. Fare clic su *Create account* (Crea account).




== Visualizza i dettagli dell'account

È possibile visualizzare l'attività delle performance per i singoli account in un formato grafico.

Le informazioni del grafico forniscono informazioni di i/o e throughput per l'account. I livelli di attività medi e di picco sono indicati in incrementi di periodi di reporting di 10 secondi. Queste statistiche includono l'attività per tutti i volumi assegnati all'account.

. Selezionare *Gestione* > *account*.
. Fare clic sull'icona azioni di un account.
. Fare clic su *View Details* (Visualizza dettagli).


Di seguito sono riportati alcuni dettagli:

* *Status*: Lo stato dell'account. Valori possibili:
+
** Attivo: Un account attivo.
** Locked (bloccato): Un account bloccato.
** Rimosso: Un account che è stato eliminato e rimosso.


* *Active Volumes* (volumi attivi): Il numero di volumi attivi assegnati all'account.
* *Compressione*: Il punteggio di efficienza della compressione per i volumi assegnati all'account.
* *Deduplica*: Il punteggio di efficienza della deduplica per i volumi assegnati all'account.
* *Thin Provisioning*: Il punteggio di efficienza del thin provisioning per i volumi assegnati all'account.
* *Efficienza complessiva*: Il punteggio di efficienza globale per i volumi assegnati all'account.




== Modificare un account

È possibile modificare un account per modificare lo stato, i segreti CHAP o il nome dell'account.

La modifica delle impostazioni CHAP in un account o la rimozione di iniziatori o volumi da un gruppo di accesso può causare la perdita improvvisa dell'accesso ai volumi da parte degli iniziatori. Per verificare che l'accesso al volume non venga perso in modo imprevisto, disconnettersi sempre dalle sessioni iSCSI che saranno interessate dalla modifica di un account o di un gruppo di accesso e verificare che gli iniziatori possano riconnettersi ai volumi dopo aver apportato modifiche alle impostazioni dell'iniziatore e del cluster.


IMPORTANT: I volumi persistenti associati ai servizi di gestione vengono assegnati a un nuovo account creato durante l'installazione o l'aggiornamento. Se si utilizzano volumi persistenti, non modificare o eliminare l'account associato.

. Selezionare *Gestione* > *account*.
. Fare clic sull'icona azioni di un account.
. Nel menu visualizzato, selezionare *Edit* (Modifica).
. *Opzionale:* modificare il *Nome utente*.
. *Opzionale:* fare clic sull'elenco a discesa *Stato* e selezionare un altro stato.
+

IMPORTANT: Se si modifica lo stato su *Locked*, tutte le connessioni iSCSI all'account vengono terminate e l'account non è più accessibile. I volumi associati all'account vengono mantenuti; tuttavia, i volumi non sono rilevabili tramite iSCSI.

. *Opzionale:* in *Impostazioni CHAP*, modificare le credenziali *Segreto iniziatore* e *Segreto di destinazione* utilizzate per l'autenticazione della sessione del nodo.
+

NOTE: Se non si modificano le credenziali *CHAP Settings*, queste rimangono invariate. Se i campi delle credenziali vengono vuoti, il sistema genera nuove password.

. Fare clic su *Save Changes* (Salva modifiche).




== Eliminare un account

È possibile eliminare un account quando non è più necessario.

Eliminare e rimuovere tutti i volumi associati all'account prima di eliminarlo.


IMPORTANT: I volumi persistenti associati ai servizi di gestione vengono assegnati a un nuovo account creato durante l'installazione o l'aggiornamento. Se si utilizzano volumi persistenti, non modificare o eliminare l'account associato.

. Selezionare *Gestione* > *account*.
. Fare clic sull'icona azioni dell'account che si desidera eliminare.
. Nel menu visualizzato, selezionare *Delete* (Elimina).
. Confermare l'azione.




== Trova ulteriori informazioni

* https://www.netapp.com/data-storage/solidfire/documentation["Pagina SolidFire and Element Resources"^]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per server vCenter"^]

