---
permalink: api/reference_element_api_account.html 
sidebar: sidebar 
keywords: account,object,accounts 
summary: 'L"oggetto account contiene informazioni su un account. Questo oggetto include solo informazioni "configurate" sull"account e non informazioni sull"utilizzo o sul runtime.' 
---
= account
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'oggetto account contiene informazioni su un account. Questo oggetto include solo informazioni "configurate" sull'account e non informazioni sull'utilizzo o sul runtime.



== Membri dell'oggetto

Questo oggetto contiene i seguenti membri:

|===
| Nome | Descrizione | Tipo 


 a| 
ID account
 a| 
L'ID account univoco per l'account.
 a| 
intero



 a| 
attributi
 a| 
Elenco delle coppie nome-valore nel formato oggetto JSON.
 a| 
Oggetto JSON



 a| 
EnableChap
 a| 
Specifica se le credenziali dell'account CHAP possono essere utilizzate da un iniziatore per accedere ai volumi.
 a| 
booleano



 a| 
InitatorSecret
 a| 
Il segreto CHAP iniziatore.
 a| 
stringa



 a| 
stato
 a| 
Lo stato corrente dell'account. Valori possibili:

* Attivo: Un account attivo.
* Locked (bloccato): Un account bloccato.
* Rimosso: Un account che è stato eliminato e rimosso.

 a| 
stringa



 a| 
StorageContainerID
 a| 
ID univoco del container di storage del volume virtuale associato a questo account.
 a| 
UUID



 a| 
TargetSecret
 a| 
Il segreto CHAP di destinazione.
 a| 
stringa



 a| 
nome utente
 a| 
Il nome utente dell'account.
 a| 
stringa



 a| 
volumi
 a| 
Un elenco di ID volume per i volumi di proprietà di questo account.
 a| 
array intero

|===


== Trova ulteriori informazioni

* xref:reference_element_api_addaccount.adoc[AddAccount]
* xref:reference_element_api_getaccountbyid.adoc[GetAccountByID]
* xref:reference_element_api_getaccountbyname.adoc[GetAccountByName]
* xref:reference_element_api_listaccounts.adoc[ListAccounts]

